using System;
using System.Collections.Generic;

namespace olexlib
{
	static class FontManager
	{
		public static class LargeFont
		{
			public static readonly bool[] C0R0 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C1R0 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, true, true, false, false, true, false, false, true, false, true, false, false, true, true, false, false, true, false, true, false, false, true, false };
			public static readonly bool[] C2R0 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true };
			public static readonly bool[] C3R0 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, false, true, false, true, false, false, true, false, true, false, false, false, true, false, false };
			public static readonly bool[] C4R0 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, true, false, true, true, false, true, false, true, false, true, false, true, false };
			public static readonly bool[] C5R0 = new[] { false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, true, true, true, false, false, true, true, false, false, false, true, false, false, false, false, false, false, false, false };
			public static readonly bool[] C6R0 = new[] { false, false, true, false, false, false, true, true, true, false, true, true, true, true, true, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C7R0 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, true, true, true, true, true, false, true, true, true, false, false, false, true, false, false };
			public static readonly bool[] C8R0 = new[] { false, false, false, true, false, false, false, true, false, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, true, false, false, false, true, false, false, false };
			public static readonly bool[] C9R0 = new[] { false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, false, false };
			public static readonly bool[] C10R0 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, false, true, false, false, true, true, true, false, false, false, false, false, false };
			public static readonly bool[] C11R0 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, false, false, false, false, false, false, false };
			public static readonly bool[] C12R0 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C13R0 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false };
			public static readonly bool[] C14R0 = new[] { false, true, true, false, false, false, false, false, true, false, false, true, true, false, false, false, false, false, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C15R0 = new[] { true, true, true, true, true, true, true, false, false, false, true, true, false, false, false, true, true, true, true, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false };
			public static readonly bool[] C0R1 = new[] { false, false, true, true, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, true, false, false, false, true, true, false, false, false, false, true, false, false };
			public static readonly bool[] C1R1 = new[] { false, false, false, true, true, false, false, false, false, true, true, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C2R1 = new[] { false, true, true, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C3R1 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true, true, true, true };
			public static readonly bool[] C4R1 = new[] { false, true, true, false, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C5R1 = new[] { true, false, true, true, false, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C6R1 = new[] { false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C7R1 = new[] { false, false, false, false, true, false, false, true, true, false, true, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C8R1 = new[] { false, false, false, true, false, false, false, false, true, false, true, true, true, true, true, false, false, true, false, false, true, true, true, true, true, false, true, false, false, false, false, true, false, false, false };
			public static readonly bool[] C9R1 = new[] { true, false, false, false, false, false, true, true, false, false, false, false, false, true, true, false, true, true, false, false, true, false, false, false, false, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C10R1 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C11R1 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, true, true, false, false, true, false, false, false, false, true, true, true, true };
			public static readonly bool[] C12R1 = new[] { false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false };
			public static readonly bool[] C13R1 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, true, true, true, true, false, true, false, true, true, false, true, false, true, true, false, true, false, true, true, false, true, true, true };
			public static readonly bool[] C14R1 = new[] { false, false, true, false, false, false, true, true, true, false, true, false, true, false, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C15R1 = new[] { false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, true, false, true, false, true, true, true, false, false, false, true, false, false };
			public static readonly bool[] C0R2 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C1R2 = new[] { false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C2R2 = new[] { false, true, false, true, false, false, true, false, true, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C3R2 = new[] { false, true, false, true, false, false, true, false, true, false, true, true, true, true, true, false, true, false, true, false, true, true, true, true, true, false, true, false, true, false, false, true, false, true, false };
			public static readonly bool[] C4R2 = new[] { false, true, false, false, false, false, true, false, true, false, false, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C5R2 = new[] { true, true, false, false, false, true, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true, true, false, false, false, true, true };
			public static readonly bool[] C6R2 = new[] { false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, true, true, false, false, true, false, false, true, true, false, true };
			public static readonly bool[] C7R2 = new[] { false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C8R2 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false };
			public static readonly bool[] C9R2 = new[] { false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false };
			public static readonly bool[] C10R2 = new[] { false, false, false, false, false, false, false, true, false, false, true, false, true, false, true, false, true, true, true, false, true, false, true, false, true, false, false, true, false, false, false, false, false, false, false };
			public static readonly bool[] C11R2 = new[] { false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, true, true, true, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false };
			public static readonly bool[] C12R2 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, false, false };
			public static readonly bool[] C13R2 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C14R2 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, true, true, false, false };
			public static readonly bool[] C15R2 = new[] { false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C0R3 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, true, true, true, false, true, false, true, true, true, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C1R3 = new[] { false, false, true, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C2R3 = new[] { false, true, true, true, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true, true, true, true };
			public static readonly bool[] C3R3 = new[] { true, true, true, true, true, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C4R3 = new[] { false, false, false, true, false, false, false, true, true, false, false, true, false, true, false, true, false, false, true, false, true, true, true, true, true, false, false, false, true, false, false, false, false, true, false };
			public static readonly bool[] C5R3 = new[] { true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C6R3 = new[] { false, false, true, true, false, false, true, false, false, false, true, false, false, false, false, true, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C7R3 = new[] { true, true, true, true, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false };
			public static readonly bool[] C8R3 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C9R3 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, true, false, false, false, false, true, false, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C10R3 = new[] { false, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, false, false, false };
			public static readonly bool[] C11R3 = new[] { false, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, false, false };
			public static readonly bool[] C12R3 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false };
			public static readonly bool[] C13R3 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C14R3 = new[] { false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false };
			public static readonly bool[] C15R3 = new[] { false, true, true, true, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false };
			public static readonly bool[] C0R4 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, true, false, true, true, false, true, true, true, true, false, true, false, false, true, false, false, false, false, false, true, true, true, true };
			public static readonly bool[] C1R4 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C2R4 = new[] { true, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false };
			public static readonly bool[] C3R4 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C4R4 = new[] { true, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false };
			public static readonly bool[] C5R4 = new[] { true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C6R4 = new[] { true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false };
			public static readonly bool[] C7R4 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C8R4 = new[] { true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C9R4 = new[] { false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C10R4 = new[] { false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C11R4 = new[] { true, false, false, false, true, true, false, false, true, false, true, false, true, false, false, true, true, false, false, false, true, false, true, false, false, true, false, false, true, false, true, false, false, false, true };
			public static readonly bool[] C12R4 = new[] { true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C13R4 = new[] { true, false, false, false, true, true, true, false, true, true, true, false, true, false, true, true, false, true, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C14R4 = new[] { true, false, false, false, true, true, false, false, false, true, true, true, false, false, true, true, false, true, false, true, true, false, false, true, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C15R4 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C0R5 = new[] { true, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false };
			public static readonly bool[] C1R5 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, true, false, true, true, false, false, true, false, false, true, true, false, true };
			public static readonly bool[] C2R5 = new[] { true, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false, true, false, true, false, false, true, false, false, true, false, true, false, false, false, true };
			public static readonly bool[] C3R5 = new[] { false, true, true, true, true, true, false, false, false, false, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, false, false, false, false, true, true, true, true, true, false };
			public static readonly bool[] C4R5 = new[] { true, true, true, true, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C5R5 = new[] { true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C6R5 = new[] { true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, false, true, false, false, true, false, true, false, false, false, true, false, false };
			public static readonly bool[] C7R5 = new[] { true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, true, false, true, true, false, true, false, true, true, false, true, false, true, false, true, false, true, false };
			public static readonly bool[] C8R5 = new[] { true, false, false, false, true, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C9R5 = new[] { true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C10R5 = new[] { true, true, true, true, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C11R5 = new[] { false, false, true, true, false, false, true, false, false, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true, true, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C12R5 = new[] { false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false };
			public static readonly bool[] C13R5 = new[] { false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, false, false };
			public static readonly bool[] C14R5 = new[] { false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C15R5 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C0R6 = new[] { false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C1R6 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C2R6 = new[] { true, false, false, false, false, true, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false };
			public static readonly bool[] C3R6 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C4R6 = new[] { false, false, false, false, true, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C5R6 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, false };
			public static readonly bool[] C6R6 = new[] { false, false, true, true, false, false, true, false, false, true, false, true, false, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false };
			public static readonly bool[] C7R6 = new[] { false, false, false, false, false, false, true, true, true, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, true, false, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C8R6 = new[] { true, false, false, false, false, true, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C9R6 = new[] { false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C10R6 = new[] { false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, true, true, false };
			public static readonly bool[] C11R6 = new[] { false, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, true, false, true, false, false, true, true, false, false, false, true, false, true, false, false, true, false, false, true };
			public static readonly bool[] C12R6 = new[] { false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C13R6 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, false, true, false, true, false, true, false, true, true, false, true, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C14R6 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C15R6 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C0R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, true, false, false, false, true, true, true, true, true, false, true, false, false, false, false, true, false, false, false, false };
			public static readonly bool[] C1R7 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, false, true, true, false, false, true, true, false, true, true, true, true, false, false, false, false, true, false, false, false, false, true };
			public static readonly bool[] C2R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false };
			public static readonly bool[] C3R7 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, true, true, false };
			public static readonly bool[] C4R7 = new[] { false, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, true, true, false };
			public static readonly bool[] C5R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true };
			public static readonly bool[] C6R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false };
			public static readonly bool[] C7R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, true, false, true, true, false, true, false, true, false, true, false, true, false };
			public static readonly bool[] C8R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true };
			public static readonly bool[] C9R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, true, false, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C10R7 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true, true, true, true };
			public static readonly bool[] C11R7 = new[] { false, false, false, true, true, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, true };
			public static readonly bool[] C12R7 = new[] { false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C13R7 = new[] { true, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, true, true, false, false, false };
			public static readonly bool[] C14R7 = new[] { false, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C15R7 = new[] { true, true, true, true, true, true, true, true, true, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true, true, true, true, true, true, true, true, true, true, true };
			public static readonly bool[] C0R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, false, true, false, false, true, false, true, false, false, true, false, true, false, false, true, true, true, false };
			public static readonly bool[] C1R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C2R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, true, true, false };
			public static readonly bool[] C3R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C4R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, true, true, true, false, false, false, false, true, false, false, false, false, true, false };
			public static readonly bool[] C5R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C6R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, true, true, true, false, false, true, false, true, false, false, true, true, true, false };
			public static readonly bool[] C7R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false };
			public static readonly bool[] C8R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, false, true, false, false, true, true, true, false, false, true, false, true, false, false, true, true, true, false };
			public static readonly bool[] C9R8 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, false, true, false, false, true, true, true, false, false, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C10R8 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true };
			public static readonly bool[] C11R8 = new[] { false, true, false, false, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true };
			public static readonly bool[] C12R8 = new[] { false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true };
			public static readonly bool[] C13R8 = new[] { false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, true, true, false, false, false, true };
			public static readonly bool[] C14R8 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, true, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C15R8 = new[] { false, true, false, false, false, false, false, true, false, false, false, true, true, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C0R9 = new[] { false, false, true, false, false, false, true, false, true, false, false, true, true, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C1R9 = new[] { false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, true, false, true, true, true, true, true, false, false, false, true, false, true, true, true, true };
			public static readonly bool[] C2R9 = new[] { false, false, false, true, false, false, false, true, false, false, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C3R9 = new[] { false, true, false, false, false, false, false, true, false, false, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C4R9 = new[] { false, false, true, false, false, false, true, false, true, false, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C5R9 = new[] { false, true, false, true, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C6R9 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, false };
			public static readonly bool[] C7R9 = new[] { false, true, false, false, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, false };
			public static readonly bool[] C8R9 = new[] { false, false, true, false, false, false, true, false, true, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, false };
			public static readonly bool[] C9R9 = new[] { false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, true, true, false, false, false, false, false, true, true, true, false };
			public static readonly bool[] C10R9 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C11R9 = new[] { false, true, false, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C12R9 = new[] { false, false, true, false, false, false, true, false, true, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C13R9 = new[] { false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C14R9 = new[] { false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C15R9 = new[] { false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C0R10 = new[] { false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C1R10 = new[] { false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, true, false };
			public static readonly bool[] C2R10 = new[] { false, false, false, true, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C3R10 = new[] { false, true, false, false, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C4R10 = new[] { false, false, true, false, false, false, true, false, true, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C5R10 = new[] { false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C6R10 = new[] { false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C7R10 = new[] { false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C8R10 = new[] { false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C9R10 = new[] { false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C10R10 = new[] { false, false, false, true, false, false, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C11R10 = new[] { false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C12R10 = new[] { false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C13R10 = new[] { false, true, false, true, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C14R10 = new[] { false, false, false, true, false, false, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true };
			public static readonly bool[] C15R10 = new[] { false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true };
			public static readonly bool[] C0R11 = new[] { false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true };
			public static readonly bool[] C1R11 = new[] { false, true, false, true, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, true, true, false, true, true, false, true };
			public static readonly bool[] C2R11 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false, false, false, true, false, false, true, true, true, false, false };
			public static readonly bool[] C3R11 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false, true, true, true, false, false };
			public static readonly bool[] C4R11 = new[] { false, false, true, false, true, false, true, false, true, false, true, false, false, false, true, true, true, false, false, true, true, false, true, false, true, true, false, false, true, true, true, false, false, false, true };
			public static readonly bool[] C5R11 = new[] { false, false, true, false, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, true };
			public static readonly bool[] C6R11 = new[] { false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C7R11 = new[] { true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C8R11 = new[] { false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C9R11 = new[] { false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C10R11 = new[] { false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C11R11 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, false, true, true, false, false, true, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, true };
			public static readonly bool[] C12R11 = new[] { false, false, true, true, false, false, true, false, false, true, false, true, false, false, true, false, true, true, true, false, false, true, false, false, true, false, true, false, false, true, true, false, true, true, false };
			public static readonly bool[] C13R11 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, true, false, true, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false };
			public static readonly bool[] C14R11 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, true, true, true, true, true };
			public static readonly bool[] C15R11 = new[] { false, false, true, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, true, true, true, true, true, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C0R12 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, true, true, true, true, false, true, false, false, false, false, false, true, true, true, false };
			public static readonly bool[] C1R12 = new[] { false, false, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false };
			public static readonly bool[] C2R12 = new[] { false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, true, false, false, true, false, false, true, true, false, false, false, true };
			public static readonly bool[] C3R12 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, true, false, false, true, false, true, false, false, true, false, true, true, true, false, true, true, false, false, false, false };
			public static readonly bool[] C4R12 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, true, false, true, false, false, true, false, true, false, false, true, false, true, false, true, false, false, true, true };
			public static readonly bool[] C5R12 = new[] { false, false, false, false, false, false, false, true, true, false, false, true, false, false, true, false, true, false, false, true, false, true, true, true, false, false, true, false, false, false, true, false, false, false, false };
			public static readonly bool[] C6R12 = new[] { true, true, true, true, true, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, true, true, true, true, true };
			public static readonly bool[] C7R12 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, true, false, true, false, false, true, false, true, false, false, true, false, false, true, true, false, false };
			public static readonly bool[] C8R12 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, true, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, true, false };
			public static readonly bool[] C9R12 = new[] { false, false, true, false, false, false, false, true, false, false, false, true, true, true, false, true, false, true, false, true, false, true, true, true, false, false, false, true, false, false, false, false, true, false, false };
			public static readonly bool[] C10R12 = new[] { false, true, true, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, true, false, true, false, false, true, false, true, false, true, true, false, true, true };
			public static readonly bool[] C11R12 = new[] { true, true, true, true, true, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true };
			public static readonly bool[] C12R12 = new[] { true, true, true, true, true, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, false, true, true, true, true, false, false, false, false, true, false, true, true, true, false };
			public static readonly bool[] C13R12 = new[] { false, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C14R12 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, true };
			public static readonly bool[] C15R12 = new[] { false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, true, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, false, false, false };
			public static readonly bool[] C0R13 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C1R13 = new[] { false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false };
			public static readonly bool[] C2R13 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C3R13 = new[] { false, true, true, true, false, false, false, false, true, false, false, true, true, true, false, false, true, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C4R13 = new[] { false, true, true, true, false, false, true, false, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C5R13 = new[] { false, true, true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C6R13 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C7R13 = new[] { false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, true, false, false };
			public static readonly bool[] C8R13 = new[] { false, false, true, false, false, false, true, false, true, false, true, true, true, true, false, true, false, false, false, true, true, true, true, true, false, true, false, false, false, false, true, false, false, false, false };
			public static readonly bool[] C9R13 = new[] { true, false, false, false, false, false, true, false, false, true, false, true, false, true, false, false, false, true, false, false, false, true, false, true, false, true, false, false, true, false, false, false, false, false, true };
			public static readonly bool[] C10R13 = new[] { true, true, true, true, true, true, false, false, false, true, true, false, true, false, false, true, true, true, false, false, true, false, true, false, false, true, false, false, false, false, true, false, false, false, false };
			public static readonly bool[] C11R13 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, true, true, true, true, true, false, true, false, false, false, false, false, true, true, false, false };
			public static readonly bool[] C12R13 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, true };
			public static readonly bool[] C13R13 = new[] { true, false, false, false, true, true, true, false, false, true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, false, false, true, true, true, false, false, false, true };
			public static readonly bool[] C14R13 = new[] { true, false, true, false, false, false, true, false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, true, false, true, false, true, false, true, false, true, false, true, false, false };
			public static readonly bool[] C15R13 = new[] { false, false, false, false, false, false, true, false, false, false, true, true, true, false, false, true, true, true, true, false, true, true, true, false, false, false, true, false, false, false, false, false, false, false, false };
			public static readonly bool[] C0R14 = new[] { true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true };
			public static readonly bool[] C1R14 = new[] { true, true, false, true, true, true, false, false, false, true, false, true, false, true, false, true, true, false, true, true, true, true, false, true, true, true, true, false, true, true, true, true, false, true, true };
			public static readonly bool[] C2R14 = new[] { true, true, true, true, true, true, true, false, true, true, true, false, true, false, true, true, false, false, false, true, true, false, true, false, true, true, false, true, false, true, true, true, true, true, true };
			public static readonly bool[] C3R14 = new[] { true, true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, false, false, true, true, false, true, false, true, true, true, false, false, true, true, true, true, true, true };
			public static readonly bool[] C4R14 = new[] { false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C5R14 = new[] { false, false, true, false, false, false, true, true, true, false, true, false, true, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C6R14 = new[] { false, false, true, false, false, false, true, false, true, false, false, true, true, true, false, false, true, false, true, false, false, true, false, true, false, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C7R14 = new[] { false, false, true, false, false, false, false, false, true, false, false, false, true, true, false, false, true, false, true, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, true };
			public static readonly bool[] C8R14 = new[] { false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false };
			public static readonly bool[] C9R14 = new[] { true, true, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, false, false };
			public static readonly bool[] C10R14 = new[] { true, true, true, true, true, false, true, true, true, true, false, false, true, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C11R14 = new[] { false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, true, true, true, false, false, true, true, true, true, false, true, true, true, true, true };
			public static readonly bool[] C12R14 = new[] { false, false, false, false, false, false, false, false, true, false, false, false, true, false, true, true, true, true, false, true, false, false, true, false, true, false, false, false, true, false, false, false, false, false, false };
			public static readonly bool[] C13R14 = new[] { false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, true, false, true, false, false, false, true, false, false, false, false, false, false, false };
			public static readonly bool[] C14R14 = new[] { false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false };
			public static readonly bool[] C15R14 = new[] { false, false, true, false, false, false, true, true, true, false, true, true, true, true, true, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false };
			public static readonly bool[] C0R15 = new[] { false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, true, true, true, true, true, false, true, true, true, false, false, false, true, false, false };
			public static readonly bool[] C1R15 = new[] { true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true, false, true };
			public static readonly bool[] C2R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C3R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C4R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C5R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C6R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C7R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C8R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C9R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C10R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C11R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C12R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C13R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C14R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			public static readonly bool[] C15R15 = new[] { false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, true, true, true, false, false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false };
			
			public static readonly Dictionary<char, bool[]> CharDict = new Dictionary<char, bool[]>
			{
				{'\0', C0R0},
				{'\'', C0R6},
				{'0', C0R3},
				{'1', C1R3},
				{'2', C2R3},
				{'3', C3R3},
				{'4', C4R3},
				{'5', C5R3},
				{'6', C6R3},
				{'7', C7R3},
				{'8', C8R3},
				{'9', C9R3},
				{'A', C1R4},
				{'B', C2R4},
				{'C', C3R4},
				{'D', C4R4},
				{'E', C5R4},
				{'F', C6R4},
				{'G', C7R4},
				{'H', C8R4},
				{'I', C9R4},
				{'J', C10R4},
				{'K', C11R4},
				{'L', C12R4},
				{'M', C13R4},
				{'N', C14R4},
				{'O', C15R4},
				{'P', C0R5},
				{'Q', C1R5},
				{'R', C2R5},
				{'S', C3R5},
				{'T', C4R5},
				{'U', C5R5},
				{'V', C6R5},
				{'W', C7R5},
				{'X', C8R5},
				{'Y', C9R5},
				{'Z', C10R5},
				{'a', C1R6},
				{'b', C2R6},
				{'c', C3R6},
				{'d', C4R6},
				{'e', C5R6},
				{'f', C6R6},
				{'g', C7R6},
				{'h', C8R6},
				{'i', C9R6},
				{'j', C10R6},
				{'k', C11R6},
				{'l', C12R6},
				{'m', C13R6},
				{'n', C14R6},
				{'o', C15R6},
				{'p', C0R7},
				{'q', C1R7},
				{'r', C2R7},
				{'s', C3R7},
				{'t', C4R7},
				{'u', C5R7},
				{'v', C6R7},
				{'w', C7R7},
				{'x', C8R7},
				{'y', C9R7},
				{'z', C10R7},
				{'(', C8R2},
				{')', C9R2},
				{'*', C10R2},
				{'+', C11R2},
				{',', C12R2},
				{'-', C13R2},
				{'.', C14R2},
				{'/', C15R2},
				{'<', C12R3},
				{'=', C13R3},
				{'>', C14R3},
				{'"', C2R2},
				{' ', C0R2},
				{'?', C15R3},
				{'!', C1R2},
				{':', C10R3},
			};
		}
	}
}

